import { describe, test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { sandbox, run, jobIdOf, waitForJob, jobResultFile, FAKE_AGY } from './helpers.mjs';

// F3 of the pool redesign: what Gemini needs to deliver a feature — project
// facts in the brief, gates it runs itself against its own database, and an
// independent review on another account before the host sees "done".

const posixOnly = { skip: process.platform === 'win32' };

function workers(sb, numbers) {
  return numbers.map((n) => {
    const bin = path.join(sb.root, `agy${n}`);
    fs.writeFileSync(bin, `#!/bin/sh\nFAKE_AGY_ID=agy${n} exec "${process.execPath}" "${FAKE_AGY}" "$@"\n`);
    fs.chmodSync(bin, 0o755);
    return bin;
  });
}

const nowS = () => Date.now() / 1000;
function quota(sb, readings) {
  const dir = path.join(sb.root, 'quota-cache');
  fs.mkdirSync(dir, { recursive: true });
  for (const [n, { gemini = 10, thirdParty = 10 }] of Object.entries(readings)) {
    fs.writeFileSync(path.join(dir, `agy-quota-profile${n}.json`), JSON.stringify({
      captured_at: nowS(),
      buckets: {
        'gemini 5h': { used_percent: gemini, resets_at: nowS() + 3600 },
        'gemini 7d': { used_percent: gemini, resets_at: nowS() + 86400 },
        '3p 5h': { used_percent: thirdParty, resets_at: nowS() + 3600 },
        '3p 7d': { used_percent: thirdParty, resets_at: nowS() + 7200 },
      },
    }));
  }
  return dir;
}

function config(sb, value) {
  fs.mkdirSync(path.join(sb.repo, '.agy-staff'), { recursive: true });
  fs.writeFileSync(path.join(sb.repo, '.agy-staff', 'config.json'), JSON.stringify(value));
}

const node = (script) => `"${process.execPath}" -e ${JSON.stringify(script)}`;

function envFor(sb, bins, dir, extra = {}) {
  return {
    PATH: [path.dirname(process.execPath), '/usr/bin', '/bin'].join(path.delimiter),
    AGY_BIN: '', AGY_POOL_BINS: bins.join(','), AGY_QUOTA_CACHE_DIR: dir,
    FAKE_AGY_RUNS_FILE: path.join(sb.root, 'runs.jsonl'), FAKE_AGY_TOUCH_FILE: 'feature.txt',
    ...extra,
  };
}

function runs(sb) {
  const file = path.join(sb.root, 'runs.jsonl');
  return fs.existsSync(file) ? fs.readFileSync(file, 'utf8').trim().split('\n').map((line) => JSON.parse(line)) : [];
}

const APPROVE = JSON.stringify({ verdict: 'approve', summary: 'looks right', findings: [], could_not_verify: [] });
const REJECT = JSON.stringify({ verdict: 'request_changes', summary: 'invented symbol', could_not_verify: [],
  findings: [{ severity: 'high', file: 'src/a.ts', line: '3', title: 'kind "propose" does not exist', detail: 'CapabilityKind has no propose' }] });

describe('F3: Gemini power', () => {
  test('facts commands are run and pasted into the implement brief', posixOnly, async () => {
    const sb = sandbox('f3-facts');
    const bins = workers(sb, [2]);
    const dir = quota(sb, { 2: {} });
    config(sb, { facts: { 'CapabilityKind values': node("console.log('read | write | apply')") }, auto_review: 'off' });
    const r = run(sb, ['implement', '--model', 'gemini-3.1-pro-high', '--worker', 'auto', '--prompt', 'add a tool'], envFor(sb, bins, dir));
    assert.equal(r.code, 0, r.stderr);
    await waitForJob(sb, jobIdOf(r.stdout));
    const prompt = runs(sb)[0].prompt;
    assert.match(prompt, /## Project facts \(generated by the companion just now\)/);
    assert.match(prompt, /### CapabilityKind values[\s\S]*read \| write \| apply/);
    assert.match(prompt, /## Grounding \(mandatory/);
  });

  test('worker_env reaches setup and gates with the worker id, and setup runs before agy', posixOnly, async () => {
    const sb = sandbox('f3-worker-env');
    const bins = workers(sb, [2]);
    const dir = quota(sb, { 2: {} });
    const marker = path.join(sb.root, 'setup-ran');
    config(sb, {
      worker_env: { APP_DB: 'app_test_{worker}' },
      worker_setup: node(`require('fs').writeFileSync(${JSON.stringify(marker)}, process.env.APP_DB)`),
      gates: { check: node("process.exit(process.env.APP_DB === 'app_test_agy2' ? 0 : 7)") },
      auto_review: 'off',
    });
    const r = run(sb, ['implement', '--model', 'gemini-3.1-pro-high', '--worker', 'auto', '--gate', 'check', '--prompt', 'x'], envFor(sb, bins, dir));
    const id = jobIdOf(r.stdout);
    assert.equal(await waitForJob(sb, id, { tries: 80 }), 'done');
    assert.equal(fs.readFileSync(marker, 'utf8'), 'app_test_agy2');
  });

  test('a failing worker_setup stops the job before agy starts', posixOnly, async () => {
    const sb = sandbox('f3-setup-fails');
    const bins = workers(sb, [2]);
    const dir = quota(sb, { 2: {} });
    config(sb, { worker_setup: node("console.log('migration exploded'); process.exit(3)"), auto_review: 'off' });
    const r = run(sb, ['implement', '--model', 'gemini-3.1-pro-high', '--worker', 'auto', '--prompt', 'x'], envFor(sb, bins, dir));
    const id = jobIdOf(r.stdout);
    assert.equal(await waitForJob(sb, id, { tries: 80 }), 'error');
    assert.equal(runs(sb).length, 0);
    assert.match(jobResultFile(sb, id), /worker_setup failed on agy2[\s\S]*migration exploded/);
  });

  test('a Gemini job is cross-reviewed on another account and stays done on approve', posixOnly, async () => {
    const sb = sandbox('f3-review-approve');
    const bins = workers(sb, [2, 3]);
    const dir = quota(sb, { 2: { thirdParty: 100 }, 3: { thirdParty: 20, gemini: 90 } });
    const r = run(sb, ['implement', '--model', 'gemini-3.1-pro-high', '--worker', 'auto', '--prompt', 'add a tool'],
      envFor(sb, bins, dir, { FAKE_AGY_REVIEW_RESPONSE: APPROVE }));
    const id = jobIdOf(r.stdout);
    assert.equal(await waitForJob(sb, id, { tries: 120 }), 'done');
    assert.deepEqual(runs(sb).map(({ id: w, model }) => [w, model]), [['agy2', 'gemini-3.1-pro-high'], ['agy3', 'claude-sonnet-4-6']]);
    assert.match(runs(sb)[1].prompt, /Symbols that do not exist/);
    assert.match(jobResultFile(sb, id), /## Cross-review\n- Round 1 \(agy3\/claude-sonnet-4-6\): approve/);
  });

  test('blocking findings get two fix rounds, then the job needs a human', posixOnly, async () => {
    const sb = sandbox('f3-review-unresolved');
    const bins = workers(sb, [2, 3]);
    const dir = quota(sb, { 2: { thirdParty: 100 }, 3: { thirdParty: 20 } });
    const r = run(sb, ['implement', '--model', 'gemini-3.1-pro-high', '--worker', 'auto', '--prompt', 'add a tool'],
      envFor(sb, bins, dir, { FAKE_AGY_REVIEW_RESPONSE: REJECT }));
    const id = jobIdOf(r.stdout);
    assert.equal(await waitForJob(sb, id, { tries: 200 }), 'attention');
    const seen = runs(sb).map(({ id: w }) => w);
    assert.deepEqual(seen, ['agy2', 'agy3', 'agy2', 'agy3', 'agy2', 'agy3']);
    assert.match(runs(sb)[2].prompt, /requires these fixes:[\s\S]*kind "propose" does not exist/);
    const result = jobResultFile(sb, id);
    assert.match(result, /Needs human: blocking findings remain after 2 fix rounds/);
    const w = run(sb, ['wait', id], envFor(sb, bins, dir));
    assert.match(w.stderr, /^STATUS: ATTENTION reason=review_unresolved/m);
  });

  test('auto_review off, and a Claude-model job under the default, are not reviewed', posixOnly, async () => {
    const sb = sandbox('f3-review-skip');
    const bins = workers(sb, [2, 3]);
    const dir = quota(sb, { 2: {}, 3: {} });
    const r = run(sb, ['implement', '--model', 'claude-sonnet-4-6', '--worker', 'auto', '--prompt', 'x'],
      envFor(sb, bins, dir, { FAKE_AGY_REVIEW_RESPONSE: APPROVE }));
    assert.equal(await waitForJob(sb, jobIdOf(r.stdout), { tries: 80 }), 'done');
    assert.equal(runs(sb).length, 1);
  });

  test('pool-mcp runs the same agy mcp command on every worker and masks secrets', posixOnly, () => {
    const sb = sandbox('f3-pool-mcp');
    const bins = workers(sb, [2, 3]);
    const dir = quota(sb, { 2: {}, 3: {} });
    const r = run(sb, ['pool-mcp', 'list'], envFor(sb, bins, dir, { FAKE_AGY_RESPONSE: 'ssh --password=hunter2' }));
    assert.equal(r.code, 0, r.stderr);
    assert.match(r.stdout, /^agy2: ok/m);
    assert.match(r.stdout, /^agy3: ok/m);
    assert.doesNotMatch(r.stdout, /hunter2/);
  });
});
